name: deploy to lambda
on: [push]
jobs:

  deploy_zip:
    name: Deploy Lambda function
    runs-on: ubuntu-latest
    steps:
      - name: Checking the source code
        uses: actions/checkout@v3
      - name: Compile & ZIP
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o main main.go && zip main.zip main
      - name: Upload ZIP File to Lambda
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: Alura-Lambda
          zip_file: main.zip